name: Docker Images CI

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push FastAPI image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./fastapi.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/car-price-fastapi:latest
          
      - name: Build and push MLflow image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./mlflow.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/car-price-mlflow:latest
          
      - name: Build and push Train image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./train.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/car-price-train:latest 
